site:
  title: Irurueta Docs
  start_page: irurueta::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/albertoirurueta/hermes.git
      branches:
        # Support version 1.3.0+
        - release_1.{3..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-units.git
      branches:
        # Support version 1.4.0+
        - release_1.{4..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-statistics.git
      branches:
        # Support version 1.4.0+
        - release_1.{4..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-sorting.git
      branches:
        # Support version 1.4.0+
        - release_1.{4..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-algebra.git
      branches:
        # Support version 1.4.0+
        - release_1.{4..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-numerical.git
      branches:
        # Support version 1.6.0+
        - release_1.{6..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/irurueta-geometry.git
      branches:
        # Support version 1.6.0+
        - release_1.{6..99}*
        - release_{2..99}*
      start_path: docs
    - url: https://github.com/albertoirurueta/ai-catalog.git
      branches:
        - main
      start_path: docs
ui:
  bundle:
    url: ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
antora:
  extensions:
    - require: "@antora/lunr-extension"
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true
asciidoc:
  attributes:
    mathjax-tex-tags: ams
    mathjax-tex-packages: ams
  extensions:
    - '@djencks/asciidoctor-mathjax'
