name: manual_publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Antora
        run: |
          npm i -D -E antora
          npm i @antora/lunr-extension
          npm i @sntke/antora-mermaid-extension
          npm i @djencks/asciidoctor-mathjax

      - name: Build Antora docs
        run: npx antora antora-playbook.yml

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          build_dir: ./build/site
          fqdn: irurueta.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
